- hosts: all
  roles:
    - base
    - docker
    - postgres
    - www
  handlers:
    - import_tasks: "global_handlers.yml"
  tags: base

- hosts: overviewer
  roles:
    - overviewer
  handlers:
    - import_tasks: "global_handlers.yml"
  tags: overviewer

- hosts: minecraft
  roles:
    - minecraft
  handlers:
    - import_tasks: "global_handlers.yml"
  tags: minecraft

- hosts: wiki
  roles:
    - postgres
  handlers:
    - import_tasks: "global_handlers.yml"
  tags: postgres

- hosts: wiki
  roles:
    - wikijs
  handlers:
    - import_tasks: "global_handlers.yml"
  tags: wiki
